.PHONY: clean All

All:
	@echo "----------Building project:[ 1-1_code_sparse_matrix - Debug ]----------"
	@cd "1-1_code_sparse_matrix" && "$(MAKE)" -f  "1-1_code_sparse_matrix.mk"
clean:
	@echo "----------Cleaning project:[ 1-1_code_sparse_matrix - Debug ]----------"
	@cd "1-1_code_sparse_matrix" && "$(MAKE)" -f  "1-1_code_sparse_matrix.mk" clean
