.PHONY: clean All

All:
	@echo "----------Building project:[ SectionString2_longest_substring - Debug ]----------"
	@cd "SectionString2_longest_substring" && "$(MAKE)" -f  "SectionString2_longest_substring.mk"
clean:
	@echo "----------Cleaning project:[ SectionString2_longest_substring - Debug ]----------"
	@cd "SectionString2_longest_substring" && "$(MAKE)" -f  "SectionString2_longest_substring.mk" clean
