.PHONY: clean All

All:
	@echo "----------Building project:[ 1-3_demo_array - Debug ]----------"
	@cd "1-2_demo_array_adt" && "$(MAKE)" -f  "1-3_demo_array.mk"
clean:
	@echo "----------Cleaning project:[ 1-3_demo_array - Debug ]----------"
	@cd "1-2_demo_array_adt" && "$(MAKE)" -f  "1-3_demo_array.mk" clean
