.PHONY: clean All

All:
	@echo "----------Building project:[ 1-1_fibunanci_dynamic_programming - Debug ]----------"
	@cd "1-1_fibunanci_dynamic_programming" && "$(MAKE)" -f  "1-1_fibunanci_dynamic_programming.mk"
clean:
	@echo "----------Cleaning project:[ 1-1_fibunanci_dynamic_programming - Debug ]----------"
	@cd "1-1_fibunanci_dynamic_programming" && "$(MAKE)" -f  "1-1_fibunanci_dynamic_programming.mk" clean
