.PHONY: clean All

All:
	@echo "----------Building project:[ 1-3_1_circular_linked_list - Debug ]----------"
	@cd "1-3_1_circular_linked_list" && "$(MAKE)" -f  "1-3_1_circular_linked_list.mk"
clean:
	@echo "----------Cleaning project:[ 1-3_1_circular_linked_list - Debug ]----------"
	@cd "1-3_1_circular_linked_list" && "$(MAKE)" -f  "1-3_1_circular_linked_list.mk" clean
