.PHONY: clean All

All:
	@echo "----------Building project:[ practiceee - Debug ]----------"
	@cd "practiceee" && "$(MAKE)" -f  "practiceee.mk"
clean:
	@echo "----------Cleaning project:[ practiceee - Debug ]----------"
	@cd "practiceee" && "$(MAKE)" -f  "practiceee.mk" clean
