.PHONY: clean All

All:
	@echo "----------Building project:[ 1-7_factorical - Debug ]----------"
	@cd "1-7_factorical" && "$(MAKE)" -f  "1-7_factorical.mk"
clean:
	@echo "----------Cleaning project:[ 1-7_factorical - Debug ]----------"
	@cd "1-7_factorical" && "$(MAKE)" -f  "1-7_factorical.mk" clean
