.PHONY: clean All

All:
	@echo "----------Building project:[ 1-1_code_chaining_open_hash - Debug ]----------"
	@cd "1-1_code_chaining_open_hash" && "$(MAKE)" -f  "1-1_code_chaining_open_hash.mk"
clean:
	@echo "----------Cleaning project:[ 1-1_code_chaining_open_hash - Debug ]----------"
	@cd "1-1_code_chaining_open_hash" && "$(MAKE)" -f  "1-1_code_chaining_open_hash.mk" clean
