.PHONY: clean All

All:
	@echo "----------Building project:[ 1-8_convert_pre_post_to_infix - Debug ]----------"
	@cd "1-8_convert_pre_post_to_infix" && "$(MAKE)" -f  "1-8_convert_pre_post_to_infix.mk"
clean:
	@echo "----------Cleaning project:[ 1-8_convert_pre_post_to_infix - Debug ]----------"
	@cd "1-8_convert_pre_post_to_infix" && "$(MAKE)" -f  "1-8_convert_pre_post_to_infix.mk" clean
