.PHONY: clean All

All:
	@echo "----------Building project:[ 1-1_insertion - Debug ]----------"
	@cd "1-1_insertion" && "$(MAKE)" -f  "1-1_insertion.mk"
clean:
	@echo "----------Cleaning project:[ 1-1_insertion - Debug ]----------"
	@cd "1-1_insertion" && "$(MAKE)" -f  "1-1_insertion.mk" clean
