.PHONY: clean All

All:
	@echo "----------Building project:[ 2_redix_sort - Debug ]----------"
	@cd "2_redix_sort" && "$(MAKE)" -f  "2_redix_sort.mk"
clean:
	@echo "----------Cleaning project:[ 2_redix_sort - Debug ]----------"
	@cd "2_redix_sort" && "$(MAKE)" -f  "2_redix_sort.mk" clean
