.PHONY: clean All

All:
	@echo "----------Building project:[ 1-6_tri_diognal_tri_band_matrix - Debug ]----------"
	@cd "1-6_tri_diognal_tri_band_matrix" && "$(MAKE)" -f  "1-6_tri_diognal_tri_band_matrix.mk"
clean:
	@echo "----------Cleaning project:[ 1-6_tri_diognal_tri_band_matrix - Debug ]----------"
	@cd "1-6_tri_diognal_tri_band_matrix" && "$(MAKE)" -f  "1-6_tri_diognal_tri_band_matrix.mk" clean
