.PHONY: clean All

All:
	@echo "----------Building project:[ excercies - Debug ]----------"
	@cd "excercies" && "$(MAKE)" -f  "excercies.mk"
clean:
	@echo "----------Cleaning project:[ excercies - Debug ]----------"
	@cd "excercies" && "$(MAKE)" -f  "excercies.mk" clean
