.PHONY: clean All

All:
	@echo "----------Building project:[ 1-4_set_operations - Debug ]----------"
	@cd "1-4_set_operations" && "$(MAKE)" -f  "1-4_set_operations.mk"
clean:
	@echo "----------Cleaning project:[ 1-4_set_operations - Debug ]----------"
	@cd "1-4_set_operations" && "$(MAKE)" -f  "1-4_set_operations.mk" clean
