.PHONY: clean All

All:
	@echo "----------Building project:[ 1-1_sparse_matrix_using_linked_list - Debug ]----------"
	@cd "1-1_sparse_matrix_using_linked_list" && "$(MAKE)" -f  "1-1_sparse_matrix_using_linked_list.mk"
clean:
	@echo "----------Cleaning project:[ 1-1_sparse_matrix_using_linked_list - Debug ]----------"
	@cd "1-1_sparse_matrix_using_linked_list" && "$(MAKE)" -f  "1-1_sparse_matrix_using_linked_list.mk" clean
