.PHONY: clean All

All:
	@echo "----------Building project:[ 1-4_Prim_sProgram - Debug ]----------"
	@cd "1-4_Prim_sProgram" && "$(MAKE)" -f  "1-4_Prim_sProgram.mk"
clean:
	@echo "----------Cleaning project:[ 1-4_Prim_sProgram - Debug ]----------"
	@cd "1-4_Prim_sProgram" && "$(MAKE)" -f  "1-4_Prim_sProgram.mk" clean
