.PHONY: clean All

All:
	@echo "----------Building project:[ practiceeee - Debug ]----------"
	@cd "practiceeee" && "$(MAKE)" -f  "practiceeee.mk"
clean:
	@echo "----------Cleaning project:[ practiceeee - Debug ]----------"
	@cd "practiceeee" && "$(MAKE)" -f  "practiceeee.mk" clean
